// nodejs/typicalbuild/react/src/ijijin-view/Alert/alert.tsx
/*
 * alert
 */

import React, { Component } from 'react'
import { CSSTransition } from 'react-transition-group'
import classnames from 'classnames'

import Mask from '../Mask'

interface AlertState {
    show: boolean;
    title?: string | undefined;
    content: string;
    noBtn?: boolean;
    btns: Array<object> | null;
    className?: any;
	maskClassName?: any;
	maskClick: any;
}

class AlertComponent extends Component<null, AlertState> {
    constructor (props: any) {
        super(props);

        this.state = {
            show: false,
            title: '',
            content: '',
            noBtn: false,
            btns: null,
            className: '',
            maskClassName: '',
            maskClick: null,
        };
    }

    /**
     * get button
     */
    getBtns = (btns: any) => {
        let _hidefunc = this.addNotice.bind(this, { show: false });
        if (!btns || !btns.length) return <a className="u-btn" onClick={_hidefunc}>确定</a>

        return btns.map((item: any) => (
            <a
                className={classnames('u-btn f-fl', item.className)}
                style={{ width: Math.floor(100 / btns.length) + '%' }}
                onClick={ item.callback || _hidefunc }
            >{ item.text }</a>
            ))
    };


    // notice
    addNotice(options: any) {
        if (!options) return false;

        this.setState(options);
    }

    render () {
        let {
            show,
            title,
            content,
            noBtn,
            btns,
            className,

            maskClassName,
            maskClick,
        } = this.state;

        return (
            <div className="ru-alert">
                <CSSTransition 
                    in={show}
                    timeout={300}
                    classNames="r-alert"
                >
                    <div className={classnames('u-win', className)}>
                        <h4 className="m-tit">{ title }</h4>
                        <div className="m-ctn" dangerouslySetInnerHTML={{ __html: content }}></div>

                        <p className={classnames('f-b_1px bt_1px', { 'z-hide': noBtn })}>
                            {
                                this.getBtns(btns)
                            }
                        </p>
                    </div>
                </CSSTransition>
                <Mask show={show} className={maskClassName} onClick={maskClick}/>
            </div>
            )
    }
}

export default AlertComponent

// client/js/plugins/vue/Alert/Alert.vue
<!-- 
 弹窗
 -->

<template>
    <section class="vu-alert">
        <transition name="v-alert">
            <div v-if="show" class="m-win" :class="className">
                <h4 class="m-tit">{{ title }}</h4>
                <div class="m-ctn" v-html="content" v-if="content"></div>
                <slot v-else></slot>

                <p class="f-b_1px bt_1px" v-show="!noBtn">
                    <a class="u-btn f-fl" 
                        v-if="btns.length"
                        v-for="(item, index) in btns" 
                        :key="index"
                        :class="item.className"
                        :style="{width: Math.floor(100 / btns.length) + '%'}"
                        @click="item.callback ? item.callback() : close()"
                    >{{ item.text }}</a>
                    <a class="u-btn" @click="close" v-if="!btns || !btns.length">确定</a>
                </p>
            </div>
        </transition>
    </section>
</template>

<script>
    import Mask from '../Mask'

    export default {
        name: 'alert',
        mixins: [Mask],
        methods: {
            close () {
                this.show = false;
            }
        },
        props: {
            content: {
                type: String,
                default: ''
            },
            title: {
                type: String,
                default: ''
            },
            className: {
                type: String,
                default: ''
            },
            btns: Array,
            show: Boolean,
            noBtn: {
                type: Boolean,
                default: false
            }
        }
    }
</script>
